In [4]:
import pandas as pd

full = pd.read_csv("../data/processed/panel/marz_year_panel_full.csv")
full[full["marz"].str.contains("Gegh", case=False, na=False)][
    ["marz","year","poverty_rate","crime_total","hospitals","population"]
].sort_values("year").head(30)

            marz  year  poverty_rate  crime_total  hospitals  population
4    Gegharkunik  2008          32.0          NaN        NaN         NaN
15   Gegharkunik  2009          40.4          NaN        NaN         NaN
26   Gegharkunik  2010          43.6          NaN        NaN         NaN
37   Gegharkunik  2011          37.0          NaN        8.0         NaN
48   Gegharkunik  2012          35.5          NaN        7.0    235380.0
59   Gegharkunik  2013          35.8          NaN        7.0    235587.0
70   Gegharkunik  2014          32.3          NaN        7.0    234079.0
81   Gegharkunik  2015          32.1          NaN        7.0    232988.0
92   Gegharkunik  2016          28.8        821.0        7.0    231794.0
103  Gegharkunik  2017          20.5        729.0        7.0    230715.0
114  Gegharkunik  2018          22.4        903.0        7.0    229711.0
125  Gegharkunik  2019          43.5       1066.0        7.0    228256.0
136  Gegharkunik  2020          48.1       1035.0        7.0    227632.0
147  Gegharkunik  2021          49.1       1250.0        7.0    227269.0
158  Gegharkunik  2022          33.9       1339.0        7.0    227778.0
169  Gegharkunik  2023          35.4       1659.0        7.0         NaN
180  Gegharkunik  2024          27.6       1398.0        7.0         NaN

In [5]:
g = full[full["marz"].str.lower() == "gegharkunik"].copy()
g = g[g["year"].between(2016, 2022)]
g[["year","poverty_rate","crime_total","hospitals","population"]]

     year  poverty_rate  crime_total  hospitals  population
92   2016          28.8        821.0        7.0    231794.0
103  2017          20.5        729.0        7.0    230715.0
114  2018          22.4        903.0        7.0    229711.0
125  2019          43.5       1066.0        7.0    228256.0
136  2020          48.1       1035.0        7.0    227632.0
147  2021          49.1       1250.0        7.0    227269.0
158  2022          33.9       1339.0        7.0    227778.0

In [6]:
g[["poverty_rate","crime_total","hospitals","population"]].isna().sum()

poverty_rate    0
crime_total     0
hospitals       0
population      0
dtype: int64